"""empty message

Revision ID: 1d684f8796ea
Revises: 3f25586fc33c
Create Date: 2020-05-15 23:45:36.506956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d684f8796ea'
down_revision = '3f25586fc33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('sheriff_campaigned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'sheriff_campaigned')
    # ### end Alembic commands ###
