"""empty message

Revision ID: 2222a0f46839
Revises: 1d684f8796ea
Create Date: 2020-08-12 23:12:13.283851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2222a0f46839'
down_revision = '1d684f8796ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('character_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'character_locked')
    # ### end Alembic commands ###
