"""votes table

Revision ID: 293ab96d7836
Revises: 374bee8eff9b
Create Date: 2020-05-03 22:00:20.505261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293ab96d7836'
down_revision = '374bee8eff9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('vote_for', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_timestamp'), 'vote', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_timestamp'), table_name='vote')
    op.drop_table('vote')
    # ### end Alembic commands ###
