"""empty message

Revision ID: 3f25586fc33c
Revises: 444ffc754833
Create Date: 2020-05-15 23:43:39.368173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f25586fc33c'
down_revision = '444ffc754833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('in_sheriff_campaign', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'in_sheriff_campaign')
    # ### end Alembic commands ###
