"""empty message

Revision ID: 444ffc754833
Revises: ad104007e5f5
Create Date: 2020-05-15 23:15:55.376040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444ffc754833'
down_revision = 'ad104007e5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('is_sheriff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'is_sheriff')
    # ### end Alembic commands ###
