"""empty message

Revision ID: 83ae300a55a6
Revises: 2222a0f46839
Create Date: 2020-08-30 18:11:32.119626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ae300a55a6'
down_revision = '2222a0f46839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('allow_to_vote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'allow_to_vote')
    # ### end Alembic commands ###
