"""empty message

Revision ID: 8674d9aa507d
Revises: ca4e5bf3c1cf
Create Date: 2020-06-25 23:59:08.263415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8674d9aa507d'
down_revision = 'ca4e5bf3c1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('in_vote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'in_vote')
    # ### end Alembic commands ###
