"""empty message

Revision ID: ad104007e5f5
Revises: 00c64a616923
Create Date: 2020-05-15 23:06:15.555562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad104007e5f5'
down_revision = '00c64a616923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('death_method', sa.String(length=120), nullable=True))
    op.add_column('player', sa.Column('is_candidate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'is_candidate')
    op.drop_column('player', 'death_method')
    # ### end Alembic commands ###
