"""empty message

Revision ID: bd8a7a1d6e9a
Revises: 83ae300a55a6
Create Date: 2020-08-30 21:25:04.505313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8a7a1d6e9a'
down_revision = '83ae300a55a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('allow_to_campaign', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'allow_to_campaign')
    # ### end Alembic commands ###
