"""empty message

Revision ID: ca4e5bf3c1cf
Revises: 1d684f8796ea
Create Date: 2020-06-19 22:19:12.042638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4e5bf3c1cf'
down_revision = '1d684f8796ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('vote_stage', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'vote_stage')
    # ### end Alembic commands ###
